# Etapa de build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY SuperBodegaWeb/SuperBodegaWeb.csproj SuperBodegaWeb/
WORKDIR /src/SuperBodegaWeb
RUN dotnet restore

COPY SuperBodegaWeb/. .
RUN dotnet publish -c Release -o /app/publish

# Etapa final
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final

# 1) Instalar fontconfig y un set de fuentes (DejaVu):
#    - fontconfig: para que Linux exponga las fuentes al sistema
#    - fonts-dejavu-core: un paquete libre de tipografías
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      fontconfig \
      fonts-dejavu-core \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "SuperBodegaWeb.dll"]
